export default {
    ROUTING_ERROR: 1,
    INVALID_TYPE_ERROR: 2,
    DATA_BASE_ERROR: 3,
    INVALID_PARAMS_ERROR: 4,
    BAD_REQUEST_ERROR: 5,
    USER_ALREADY_EXISTS: 6,
    INVALID_CREDENTIALS: 7,
    PRODUCT_NOT_FOUND:8,
    CART_NOT_FOUND:9,
    USER_NOT_FOUND:10,
    PRODUCT_INCART_NF:11,
  };

